export const slides = [
  {
    id: "villaKhezershahr",
    titleKey: "project.villaKhezershahr.titleProject",
    subtitleKey: "project.villaKhezershahr.subtitle",
    location: "Khezershahr, Mazandaran",
    landArea: "280 sqm",
    builtArea: "450 sqm",
    designTeam: { architect: "Ghazaleh Ataei" },
    year: { design: "2025", completion: "2026" },
    textKey: "project.villaKhezershahr.text",
        images: [
      "/projects/third/3-asli.jpg",
      "/projects/third/3.jpg",
      "/projects/third/33.jpg",
      "/projects/third/333.jpg",
      "/projects/third/333.jpg",
    ],
  },
  {
    id: "Bedroom design",
    titleKey: "project.apartmentInterior.titleProject",
    subtitleKey: "project.apartmentInterior.subtitle",
    location: "Babol, Mazandaran",
    landArea: "220 sqm",
    builtArea: "400 sqm",
    designTeam: { architect: "Ghazaleh Ataei" },
    year: { design: "2024", completion: "2025" },
    textKey: "project.apartmentInterior.text",
    images: [
      "/projects/second/2.jpg",
      "/projects/second/22.jpg",
      "/projects/second/222.jpg",
      "/projects/second/2222.jpg",
      "/projects/second/2222.jpg",
    ],
  },
  {
    id: "Living Roome Design",
    titleKey: "project.duplexElahieh.titleProject",
    subtitleKey: "project.duplexElahieh.subtitle",
    location: "babol, Mazandaran",
    landArea: "200 sqm",
    builtArea: "340 sqm",
    designTeam: { architect: "Ghazaleh Ataei" },
    year: { design: "2025", completion: "2025" },
    textKey: "project.duplexElahieh.text",
    images: [
      "/projects/first/0-double living room.jpg",
      "/projects/first/0-living room 01.jpg",
      "/projects/first/0-living room 2.jpg",
      "/projects/first/0-Tv wall.jpg",
      "/projects/first/0-Tv wall.jpg",
    ],
  },
];