export const slides = [
  {
    id: 1,
    titleProject: "Vila Khezershahr",
    subtitle: "Residential – Villa",
    location: "Khezershahr, Mazandaran",
    landArea: "280 sqm",
    builtArea: "450 sqm",
    designTeam: { architect: "Ghazaleh Ataei" },
    year: { design: "2025", completion: "2026" },
    text: "project.villaKhezershahr.text",
    images: [
      "/projects/third/3-asli.jpg",
      "/projects/third/3.jpg",
      "/projects/third/33.jpg",
      "/projects/third/333.jpg",
      "/projects/third/333.jpg",
    ],
  },
  {
    id: 2,
    titleProject: "Zeytoon Residential Complex, Shiraz",
    subtitle: "Residential – Apartment",
    location: "Zeytoon Blvd., Alley 7, Shiraz",
    landArea: "1200 sqm",
    builtArea: "3500 sqm",
    designTeam: { architect: "Ghazaleh Ataei" },
    year: { design: "2024", completion: "2026" },
    text: "projects.zeytoonResidential.text",
    images: [
      "/projects/second/2.jpg",
      "/projects/second/22.jpg",
      "/projects/second/222.jpg",
      "/projects/second/2222.jpg",
      "/projects/second/2222.jpg",
    ],
  },
  {
    id: 3,
    title: "Duplex Apartment, Elahieh",
    subtitle: "Residential – Renovation",
    location: "Elahieh St., No. 34, Tehran",
    landArea: "200 sqm",
    builtArea: "340 sqm",
    designTeam: { architect: "Ghazaleh Ataei" },
    year: { design: "2025", completion: "2025" },
    text: "projects.duplexElahieh.text",
    images: [
      "/projects/first/0-double living room.jpg",
      "/projects/first/0-living room 01.jpg",
      "/projects/first/0-living room 2.jpg",
      "/projects/first/0-Tv wall.jpg",
      "/projects/first/0-Tv wall.jpg",
    ],
  },
];