export const slides = [
  {
    id: 1,
    title: "Twin Villa, Niavaran",
    subtitle: "Residential – Villa",
    location: "Niavaran St., No. 18, District 1, Tehran",
    landArea: "450 sqm",
    builtArea: "780 sqm",
    designTeam: { architect: "Ghazaleh Ataei" },
    year: { design: "2025", completion: "2026" },
    text: "The Twin Villa in Niavaran is designed with inspiration from modern and vernacular architecture. Using natural materials and integrating indoor and outdoor spaces, this project offers a unique experience of living within the urban nature.",
    images: [
      "/projects/third/3-asli.jpg",
      "/projects/third/3.jpg",
      "/projects/third/33.jpg",
      "/projects/third/333.jpg",
      "/projects/third/333.jpg",
    ],
  },
  {
    id: 2,
    title: "Zeytoon Residential Complex, Shiraz",
    subtitle: "Residential – Apartment",
    location: "Zeytoon Blvd., Alley 7, Shiraz",
    landArea: "1200 sqm",
    builtArea: "3500 sqm",
    designTeam: { architect: "Ghazaleh Ataei" },
    year: { design: "2024", completion: "2026" },
    text: "Zeytoon Residential Complex is designed with an approach to open and flexible apartments. Emphasizing natural lighting and vertical gardens, this project enhances the quality of urban living.",
    images: [
      "/projects/second/2.jpg",
      "/projects/second/22.jpg",
      "/projects/second/222.jpg",
      "/projects/second/2222.jpg",
      "/projects/second/2222.jpg",
    ],
  },
  {
    id: 3,
    title: "Duplex Apartment, Elahieh",
    subtitle: "Residential – Renovation",
    location: "Elahieh St., No. 34, Tehran",
    landArea: "200 sqm",
    builtArea: "340 sqm",
    designTeam: { architect: "Ghazaleh Ataei" },
    year: { design: "2025", completion: "2025" },
    text: "Renovation of the duplex apartment in Elahieh with a minimalist approach and maximum space utilization. Combining neutral colors and luxury materials, this project creates a modern and peaceful atmosphere.",
    images: [
      "/projects/first/0-double living room.jpg",
      "/projects/first/0-living room 01.jpg",
      "/projects/first/0-living room 2.jpg",
      "/projects/first/0-Tv wall.jpg",
      "/projects/first/0-Tv wall.jpg",
    ],
  },
];
